# Generated by Django 3.0.6 on 2020-06-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remaininginstock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='img/')),
                ('amountperpack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(max_length=100)),
                ('amountperdosage', models.FloatField()),
                ('manufacturer', models.CharField(max_length=150)),
            ],
        ),
    ]
