# Generated by Django 3.0.6 on 2020-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
